import {{
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
}} from 'twenty-shared/types';

import {{ type FlatFieldMetadata }} from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import {{ type AllStandardObjectFieldName }} from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {{
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
}} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import {{ createStandardRelationFieldFlatMetadata }} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildLeadBusinessDetailStandardFlatFieldMetadatas = ({{
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}}: Omit<
  CreateStandardFieldArgs<'leadBusinessDetail', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'leadBusinessDetail'>, FlatFieldMetadata> => ({{
  id: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: 'Id',
      description: 'Id',
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  createdAt: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Creation date',
      description: 'Creation date',
      icon: 'IconCalendar',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  updatedAt: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Last update',
      description: 'Last time the record was changed',
      icon: 'IconCalendarClock',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  deletedAt: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Deleted at',
      description: 'Date when the record was deleted',
      icon: 'IconCalendarMinus',
      isNullable: true,
      isUIReadOnly: true,
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  employmentType: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'employmentType',
      type: FieldMetadataType.TEXT,
      label: 'Employment Type',
      description: 'Type of employment',
      icon: 'IconBriefcase',
      isNullable: true,
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  industry: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'industry',
      type: FieldMetadataType.TEXT,
      label: 'Industry',
      description: 'Industry type',
      icon: 'IconBuilding',
      isNullable: true,
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  ownership: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'ownership',
      type: FieldMetadataType.TEXT,
      label: 'Ownership',
      description: 'Ownership type',
      icon: 'IconUsers',
      isNullable: true,
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  businessType: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'businessType',
      type: FieldMetadataType.TEXT,
      label: 'Business Type',
      description: 'Type of business',
      icon: 'IconCategory',
      isNullable: true,
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  constitution: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'constitution',
      type: FieldMetadataType.TEXT,
      label: 'Constitution',
      description: 'Business constitution',
      icon: 'IconFileText',
      isNullable: true,
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  yearsInBusiness: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'yearsInBusiness',
      type: FieldMetadataType.NUMBER,
      label: 'Years in Business',
      description: 'Number of years in business',
      icon: 'IconClock',
      isNullable: true,
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  monthlyNetSalary: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'monthlyNetSalary',
      type: FieldMetadataType.NUMBER,
      label: 'Monthly Net Salary',
      description: 'Monthly net salary or income',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  otherInfo: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'otherInfo',
      type: FieldMetadataType.TEXT,
      label: 'Other Information',
      description: 'Additional business information',
      icon: 'IconInfoCircle',
      isNullable: true,
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  createdBy: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: 'Created by',
      description: 'The creator of the record',
      icon: 'IconCreativeCommonsSa',
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {{
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      }},
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  updatedBy: createStandardFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: 'Updated by',
      description: 'The workspace member who last updated the record',
      icon: 'IconUserCircle',
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {{
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      }},
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
  lead: createStandardRelationFieldFlatMetadata({{
    objectName,
    workspaceId,
    context: {{
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'lead',
      label: 'Lead',
      description: 'Lead related to the business detail',
      icon: 'IconUser',
      isNullable: false,
      targetObjectName: 'lead',
      targetFieldName: 'leadBusinessDetail',
      settings: {{
        relationType: RelationType.ONE_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'leadId',
      }},
    }},
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }}),
}});
